baseURL = 'https://junminjang.github.io/'
languageCode = 'en-us'
title = 'Junmin Jang Blog'
theme = 'nostyleplease'

[params]
  author = "Junmin Jang"
  description = "A minimal blog"
  # Enable MathJax
  mathjax = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
